/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package io.github.oxisto.cppparser

import java.nio.file.Paths
import kotlin.test.Test
import kotlin.test.assertNotNull
import kotlin.test.assertTrue

class ParserTest {
  @Test
  fun testParse() {
    val parser = Parser()

    val tu = parser.parse(Paths.get("src", "test", "resources", "declarations.cpp"))
    assertNotNull(tu)
  }
}
